USE week12;
UPDATE boats SET bcolor = "light_red"
WHERE bid = (5);
UPDATE boats SET bcolor = "ligh_red"
WHERE bid = (6);
UPDATE boats SET bcolor = "dark_green"
WHERE bid = (7);
UPDATE boats SET bcolor = "red"
WHERE bid = (8);
UPDATE boats SET bcolor = "brown"
WHERE bid = (9);
UPDATE boats SET bcolor = "black"
WHERE bid = (10);
UPDATE boats SET bcolor = "dark_blue"
WHERE bid = (11);
UPDATE boats SET bcolor = "bluish_green"
WHERE bid = (12);
UPDATE boats SET bcolor = "dark_yellow"
WHERE bid = (13);
UPDATE boats SET bcolor = "pinkish_brown"
WHERE bid = (14);
UPDATE boats SET bcolor = "light_blue"
WHERE bid = (15);
UPDATE boats SET bcolor = "dark_green"
WHERE bid = (16);
UPDATE boats SET bcolor = "wine_red"
WHERE bid = (17);
UPDATE boats SET bcolor = "light_green"
WHERE bid = (18);
UPDATE boats SET bcolor = "light_yellow"
WHERE bid = (19);
UPDATE boats SET bcolor = "dark_green"
WHERE bid = (20);
UPDATE boats SET bcolor = "dark_blue"
WHERE bid = (21);
UPDATE boats SET bcolor = "light_green"
WHERE bid = (22);
UPDATE boats SET bcolor = "bluish_purple"
WHERE bid = (23);
UPDATE boats SET bcolor = "dark_purple"
WHERE bid = (24);
