USE week12;
UPDATE sailors SET rating = (5)
WHERE sid = (1);
UPDATE sailors SET rating = (6)
WHERE sid = (2);
UPDATE sailors SET rating = (7)
WHERE sid = (3);
UPDATE sailors SET rating = (6)
WHERE sid = (4);
UPDATE sailors SET rating = (9)
WHERE sid = (5);
UPDATE sailors SET rating = (9)
WHERE sid = (6);
UPDATE sailors SET rating = (3)
WHERE sid = (7);
UPDATE sailors SET rating = (9)
WHERE sid = (8);
UPDATE sailors SET rating = (10)
WHERE sid = (9);
UPDATE sailors SET rating = (5)
WHERE sid = (10);
UPDATE sailors SET rating = (4)
WHERE sid = (11);
UPDATE sailors SET rating = (7)
WHERE sid = (12);
UPDATE sailors SET rating = (5)
WHERE sid = (13);
UPDATE sailors SET rating = (8)
WHERE sid = (14);
UPDATE sailors SET rating = (9)
WHERE sid = (15);
UPDATE sailors SET rating = (3)
WHERE sid = (16);
UPDATE sailors SET rating = (8)
WHERE sid = (17);
UPDATE sailors SET rating = (4)
WHERE sid = (18);
UPDATE sailors SET rating = (5)
WHERE sid = (19);
UPDATE sailors SET rating = (10)
WHERE sid = (20);
UPDATE sailors SET rating = (9)
WHERE sid = (21);
UPDATE sailors SET rating = (5)
WHERE sid = (502);
UPDATE sailors SET rating = (9)
WHERE sid = (23);
UPDATE sailors SET rating = (6)
WHERE sid = (24);
UPDATE sailors SET rating = (6)
WHERE sid = (25);
UPDATE sailors SET rating = (4)
WHERE sid = (26);
UPDATE sailors SET rating = (10)
WHERE sid = (27);
UPDATE sailors SET rating = (4)
WHERE sid = (28);
UPDATE sailors SET rating = (7)
WHERE sid = (503);
UPDATE sailors SET rating = (4)
WHERE sid = (30);
UPDATE sailors SET rating = (5)
WHERE sid = (504);
UPDATE sailors SET rating = (9)
WHERE sid = (505);
UPDATE sailors SET rating = (8)
WHERE sid = (33);
UPDATE sailors SET rating = (4)
WHERE sid = (34);
UPDATE sailors SET rating = (6)
WHERE sid = (35);
UPDATE sailors SET rating = (10)
WHERE sid = (36);
UPDATE sailors SET rating = (7)
WHERE sid = (37);
UPDATE sailors SET rating = (4)
WHERE sid = (38);
UPDATE sailors SET rating = (9)
WHERE sid = (39);
UPDATE sailors SET rating = (3)
WHERE sid = (40);
UPDATE sailors SET rating = (10)
WHERE sid = (41);
UPDATE sailors SET rating = (9)
WHERE sid = (42);
UPDATE sailors SET rating = (4)
WHERE sid = (43);
UPDATE sailors SET rating = (4)
WHERE sid = (44);
UPDATE sailors SET rating = (10)
WHERE sid = (45);
UPDATE sailors SET rating = (9)
WHERE sid = (46);
UPDATE sailors SET rating = (3)
WHERE sid = (47);
UPDATE sailors SET rating = (5)
WHERE sid = (48);
UPDATE sailors SET rating = (2)
WHERE sid = (49);
UPDATE sailors SET rating = (6)
WHERE sid = (50);
UPDATE sailors SET rating = (8)
WHERE sid = (51);
UPDATE sailors SET rating = (6)
WHERE sid = (52);
UPDATE sailors SET rating = (8)
WHERE sid = (53);
UPDATE sailors SET rating = (4)
WHERE sid = (54);
UPDATE sailors SET rating = (6)
WHERE sid = (55);
UPDATE sailors SET rating = (4)
WHERE sid = (56);
UPDATE sailors SET rating = (3)
WHERE sid = (57);
UPDATE sailors SET rating = (4)
WHERE sid = (506);
UPDATE sailors SET rating = (5)
WHERE sid = (59);
UPDATE sailors SET rating = (5)
WHERE sid = (60);
UPDATE sailors SET rating = (6)
WHERE sid = (61);
UPDATE sailors SET rating = (3)
WHERE sid = (62);
UPDATE sailors SET rating = (4)
WHERE sid = (63);
UPDATE sailors SET rating = (4)
WHERE sid = (506);
UPDATE sailors SET rating = (8)
WHERE sid = (65);
UPDATE sailors SET rating = (9)
WHERE sid = (66);
UPDATE sailors SET rating = (4)
WHERE sid = (67);
UPDATE sailors SET rating = (6)
WHERE sid = (68);
UPDATE sailors SET rating = (7)
WHERE sid = (69);
UPDATE sailors SET rating = (9)
WHERE sid = (70);
UPDATE sailors SET rating = (3)
WHERE sid = (507);
UPDATE sailors SET rating = (3)
WHERE sid = (72);
UPDATE sailors SET rating = (2)
WHERE sid = (73);
UPDATE sailors SET rating = (4)
WHERE sid = (508);
UPDATE sailors SET rating = (6)
WHERE sid = (75);
UPDATE sailors SET rating = (4)
WHERE sid = (76);
UPDATE sailors SET rating = (7)
WHERE sid = (77);
UPDATE sailors SET rating = (7)
WHERE sid = (78);
UPDATE sailors SET rating = (10)
WHERE sid = (79);
UPDATE sailors SET rating = (7)
WHERE sid = (80);
UPDATE sailors SET rating = (6)
WHERE sid = (81);
UPDATE sailors SET rating = (4)
WHERE sid = (82);
UPDATE sailors SET rating = (6)
WHERE sid = (83);
UPDATE sailors SET rating = (9)
WHERE sid = (84);
UPDATE sailors SET rating = (4)
WHERE sid = (509);
UPDATE sailors SET rating = (9)
WHERE sid = (86);
UPDATE sailors SET rating = (9)
WHERE sid = (87);
UPDATE sailors SET rating = (9)
WHERE sid = (88);
UPDATE sailors SET rating = (6)
WHERE sid = (89);
UPDATE sailors SET rating = (3)
WHERE sid = (90);
UPDATE sailors SET rating = (5)
WHERE sid = (91);
UPDATE sailors SET rating = (10)
WHERE sid = (92);
UPDATE sailors SET rating = (10)
WHERE sid = (93);
UPDATE sailors SET rating = (10)
WHERE sid = (94);
UPDATE sailors SET rating = (10)
WHERE sid = (510);
UPDATE sailors SET rating = (2)
WHERE sid = (96);
UPDATE sailors SET rating = (2)
WHERE sid = (97);
UPDATE sailors SET rating = (9)
WHERE sid = (98);
UPDATE sailors SET rating = (5)
WHERE sid = (99);
UPDATE sailors SET rating = (2)
WHERE sid = (100);
